#spring:
#  profiles:
#    active: local
---
spring:
  profiles:
    group:
      dev:
        - common
        - development
        - port_8080
      production-set1:
        - common
        - production
        - port_9001
      production-set2:
        - common
        - production
        - port_9002
---
spring:
  config:
    activate:
      on-profile: common

  pid:
    file: /home/ec2-user/app/step2/springaws.pid

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    #        use_sql_comments: true
    #    show-sql: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      enabled: 'true'
      max-request-size: 30MB
      max-file-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 440169512538-1005ef9rqk59vrjou92vahrjfre7enum.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
---
spring:
  config:
    activate:
      on-profile: port_8080

server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: port_9001

server:
  port: 9001
---
spring:
  config:
    activate:
      on-profile: port_9002

server:
  port: 9002
---
spring:
  config:
    activate:
      on-profile: development

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springaws
    url: jdbc:mysql://localhost:3306/springaws?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    password: gudrhs11

file:
  dir: C:/springAws/attachedFiles/
  thumbnailDir : C:/springAws/thumbnail/
---
spring:
  config:
    activate:
      on-profile: production

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: springaws
    url: jdbc:mysql://springboot-webservice.c7brf6sdt5ut.ap-northeast-2.rds.amazonaws.com:3306/webservice?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    password: gudrhs11

---











